# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CoderZeaho/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'
inhibit_all_warnings!

target 'WJKAudioPlayerDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for WJKAudioPlayerDemo

pod 'AFNetworking', '~> 3.1.0'			# 网络框架
pod 'SDWebImage', '~> 3.7.2'			# 网络图片加载框架
pod 'Masonry', '~> 1.0.2'			# 页面适配框架
pod 'CategoryKit-Additions', '~> 1.0.0'         # 类目

end
